### ISSUE TITLE
Can't use this neat package with React Native 0.56

### ISSUE THREAD

**Issue by gitowiec** [evanjmg/react-native-home-pressed#2]
Here is the stack trace. If I would know how to fix this I would set up a PR.

```
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugApk'.
   > A problem occurred configuring project ':react-native-home-pressed'.
      > The SDK Build Tools revision (23.0.1) is too low for project ':react-native-home-pressed'. Minimum required is 25.0.0

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

```
----
### Edit
I just gave it a shot, here is PR https://github.com/evanjmg/react-native-home-pressed/pull/3
It compiles and my app runs ok.

**Comment by evanjmg** [comment]
Thanks for the PR - want to keep the minSDK low for more support but otherwise looks good. Here's my commit 
https://github.com/evanjmg/react-native-home-pressed/commit/8cdfd734dc1d787ad29de16092c5741530b825a5 and release https://www.npmjs.com/package/react-native-home-pressed
